// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkBOW33-UNm_8jMpiqeAWWLmLpTG4Xiz4',
    appId: '1:407408601161:web:428887cdaa2880a36a7798',
    messagingSenderId: '407408601161',
    projectId: 'chat-app-51f11',
    authDomain: 'chat-app-51f11.firebaseapp.com',
    storageBucket: 'chat-app-51f11.appspot.com',
    measurementId: 'G-BZCPBBYF5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2smfeYTcETdRmZM074ws6mMsFTf0qZBE',
    appId: '1:407408601161:android:4b963dcae2de93926a7798',
    messagingSenderId: '407408601161',
    projectId: 'chat-app-51f11',
    storageBucket: 'chat-app-51f11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZrjd5S-SakwkK-eggo4PymNifQ76oM6Y',
    appId: '1:407408601161:ios:3890379ad4d375516a7798',
    messagingSenderId: '407408601161',
    projectId: 'chat-app-51f11',
    storageBucket: 'chat-app-51f11.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZrjd5S-SakwkK-eggo4PymNifQ76oM6Y',
    appId: '1:407408601161:ios:e8e65462a7a9eff56a7798',
    messagingSenderId: '407408601161',
    projectId: 'chat-app-51f11',
    storageBucket: 'chat-app-51f11.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
